/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 lap.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import image from '../images/logo.jpg'
import EffectContainerSmall from '../../components/home/EffectContainerSmall'

export function Model(props) {
  const { nodes, materials } = useGLTF('/src/assets/3DModels/lap.glb')
  return (
    <group {...props} dispose={null} scale={1.5} rotation={[0, Math.PI, 0]}>
      <group position={[0.002, -0.038, 0.414]} rotation={[0.014, 0, 0]}>
        <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Cube008'].geometry} material={materials.aluminium} >
            <Html className="text-black" rotation-x={-Math.PI / 2} position={[0, -0.2, -0.09]} transform occlude>
              <div className="text-black -scale-x-100 text-2xl select-none" onPointerDown={(e) => e.stopPropagation()}>
                K A V I S H K A
              </div>
            </Html>
          </mesh>
          <mesh geometry={nodes['Cube008_1'].geometry} material={materials['matte.001']} />
          <mesh geometry={nodes['Cube008_2'].geometry} material={materials['matte.001']}>
            <Html className="bg-black" rotation-x={-Math.PI / 2} position={[0, 0.05, -0.09]} transform occlude>
              <div className="bg-black" onPointerDown={(e) => e.stopPropagation()}>
                <EffectContainerSmall />
              </div>
            </Html>
          </mesh>
        </group>
      </group>
      <mesh geometry={nodes.keyboard.geometry} material={materials.keys} position={[1.793, 0, 3.451]} />
      <group position={[0, -0.1, 3.394]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.aluminium} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.trackpad} />
      </group>
      <mesh geometry={nodes.touchbar.geometry} material={materials.touchbar} position={[0, -0.027, 1.201]} />
    </group>
  )
}

useGLTF.preload('/src/assets/3DModels/lap.glb')
